import React from 'react';
import ModalImage from "react-modal-image";
import {Link} from '../../../../CommonStyles';

import CommonProjectPage from '../../CommonProjectPage';
import Pic1 from './assets/ex1.png';
import Pic2 from './assets/ex2.png';
import Pic3 from './assets/ex3.png';
import Pic4 from './assets/ex4.png';
import Pic5 from './assets/ex5.png';

type Props = {
    onLoad: () => void
};

const ProjectPage = (props: Props) => {
    return (
        <CommonProjectPage onLoad={props.onLoad}>
            <h2>Infinite 3D terrain</h2>
            <p>
                This is a 3D terrain engine written for the <Link href="https://drive.google.com/open?id=0B7x6g4c3-UJfV2NwbkE0MVhPY1E">MSc thesis</Link>.
                The engine renders infinite terrain (when moving around it generates necessary terrain parts) and exposes very easy api to create many
                biomes on the terrain. The biomes may change according to latitude value or may be spread
                randomly ignoring the latitude. Each of them has its own function to generate shape of the landscape.
                Also other parts of the system are highly customisable - all parameters have been described in
                the thesis (like cell size, longitude change speed, dissolving factor, layers number, blur, quad size etc.).
                The water is not finished yet (it's generated only as a simple plane in one place).
            </p>

            <ModalImage small={Pic1} large={Pic1} />
            <ModalImage small={Pic2} large={Pic2} />
            <ModalImage small={Pic3} large={Pic3} />
            <ModalImage small={Pic4} large={Pic4} />

            <p>
                Together with the engine I have created a map viewer which allows to look at the entire terrain
                that has been generated by the engine. It shows the terrain as a heightmap or a normal map.
            </p>

            <ModalImage small={Pic5} large={Pic5} />
        </CommonProjectPage>
    );
};

export default ProjectPage;